#include <iostream>
#include <iomanip>
#include <cstdlib>
#include <string>
#include <sstream>
#include <cstring>
#include <sstream>
#include <vector>
#include <fstream>
#include <stdio.h>
#include <windows.h>
#include <fstream>
#include <list>
